l_english:
 PRODUCTION_PRODUCTION_LABEL:0 "生产"
 PRODUCTION_EQUIPMENTPOOL_LABEL:0 "存量"
 PRODUCTION_EFFICIENCY_LABEL:0 "§T效率§!"
 PRODUCTION_EQUIPMENT_LABEL:0 "装备"
 PRODUCTION_ADJUSTERS_LABEL:0 "调整"
 PRODUCTION_MATERIALS_LABEL:0 "原料"
 PRODUCTION_FACTORIES_LABEL:0 "工业"
 PRODUCTION_OPERATIONAL_ARMS_FACTORIES_LABEL:0 "军用工厂"
 PRODUCTION_OPERATIONAL_DOCKYARDS_LABEL:0 "海军船坞"
 PRODUCTION_OPERATIONAL_FACTORIES_LABEL:0 "民用工厂"
 PRODUCTION_AVAILABLE_ARMS_FACTORIES_LABEL:0 "可用军用工厂"
 PRODUCTION_AVAILABLE_DOCKYARDS_LABEL:0 "可用海军船坞"
 PRODUCTION_AVAILABLE_FACTORIES_LABEL:0 "可用民用工厂"
 PRODUCTION_OPERATIONAL_FACTORIES_VALUE:0 "$VALUE$/$TOT$"
 PRODUCTION_MILITARY_LABEL:0 "§T陆军和空军装备§!"
 PRODUCTION_NAVAL_LABEL:0 "§T海军装备§!"
 PRODUCTION_BUILDINGS_LABEL:0 "§T建筑施工§!"
 PRODUCTION_PRODUCING_DAILY:0 "$AMOUNT$/日"
 PRODUCTION_PRODUCING_WEEKLY:0 "$AMOUNT$/周"
 PRODUCTION_PRODUCING_MONTHLY:0 "$AMOUNT$/月"
 PRODUCTION_PRODUCING_YEARLY:0 "$AMOUNT$/年"
 PRODUCTION_PRODUCING_ETA_DATE:0 "下次完成日期: $DATE$"
 PRODUCTION_REPAIRING_ETA_DATE:0 "修复完成日期: $DATE$"
 PRODUCTION_PRODUCING_ETA_DAYS:0 "$AMOUNT$天内"
 PRODUCTION_PRODUCING_ETA_WEEKS:0 "$AMOUNT$周内"
 PRODUCTION_PRODUCING_ETA_MONTHS:0 "$AMOUNT$月内"
 PRODUCTION_PRODUCING_ETA_YEARS:0 "$AMOUNT$年内"
 PRODUCTION_PRODUCING_NEVER:0 "§R无已分配工厂§!"
 PRODUCTION_PRODUCING_NONE:0 "§R无§!"
 PRODUCTION_CAN_NOT_DEPLOY:0 "§R无法部署§!"
 PRODUCTION_CAN_NOT_DEPLOY_MANPOWER:0 "人力资源不足"
 PRODUCTION_INCREASE_PRIORITY_LABEL:0 "§G单击§H增加优先§!\nShift+单击使得生产获得§H最高优先§!。§!"
 PRODUCTION_DECREASE_PRIORITY_LABEL:0 "§G单击§H增加优先§!\nShift+单击使得生产获得§H最低优先§!。§!"
 PRODUCTION_PRIORITY_DELAYED:0 "相对于低优先的生产线，资源会优先配置给拥有更高优先的生产线。"
 PRODUCTION_EFFICIENCY:0 "£prod_eff §T生产效率: $AMOUNT|H1%$§!"
 PRODUCTION_EFFICIENCY_MOD:0 "£prod_eff §T生产效率: $AMOUNT|Y1%$§!\n"
 PRODUCTION_EFFICIENCY_WITH_GAIN:0 "£prod_eff §T生产效率: $AMOUNT|H1%$§!（$GAIN|H3%$每周）"
 PRODUCTION_EFFICIENCY_DESC:0 "§T工厂平均生产效率。\n生产效率每单位（这些单位由已激活的工厂平均分离出来）增加$VALUE|H=2$%§!"
 PRODUCTION_RESOURCE_PENALTY:0 "§T缺少资源: $AMOUNT|R1%$§!"
 PRODUCTION_ASSIGN_EQUIPMENT:0 "§T分配装备，开始生产。§!"
 PRODUCTION_MATERIALS_OIL:0 "石油"
 PRODUCTION_MATERIALS_ALUMINIUM:0 "铝"
 PRODUCTION_MATERIALS_RUBBER:0 "橡胶"
 PRODUCTION_MATERIALS_CHROMIUM:0 "铬"
 PRODUCTION_MATERIALS_STEEL:0 "钢"
 PRODUCTION_MATERIALS_TUNGSTEN:0 "钨"
 PRODUCTION_MATERIAL_VAL:0 "$VALUE|0H$"
 PRODUCTION_VEHICLES_BUTTON:0 "生产装甲车辆"
 PRODUCTION_VEHICLES_BUTTON_DISABLED:0 "装甲车辆§R还未发明§!!"
 PRODUCTION_INFANTRY_BUTTON:0 "生产步兵与炮兵装备"
 PRODUCTION_INFANTRY_BUTTON_DISABLED:0 "步兵与炮兵装备§R还未发明§!!"
 PRODUCTION_AIRCRAFT_BUTTON:0 "生产飞行器"
 PRODUCTION_AIRCRAFT_BUTTON_DISABLED:0 "飞行器§R还未发明§!!"
 PRODUCTION_SHIPS_BUTTON:0 "建造舰队"
 PRODUCTION_SHIPS_BUTTON_DISABLED:0 "舰船§R还未发明§!!"
 PRODUCTION_CONSUMER_GOODS_VALUE:0 "$VALUE$"
 PRODUCTION_CONSUMER_GOODS:0 "生活消费品"
 PRODUCTION_CONSUMER_GOODS_LABEL:0 "§H生活消费品§!"
 PRODUCTION_CONSUMER_GOODS_DESC:0 "在我们现行经济政策下，民众期望我们工厂总数的$PERCENTAGE|H0%$用来生产消费品。只有民用工厂才能满足这种需求，剩余的$OPERATIONAL|H$中$TRADE_USABLE|H$可以进行贸易。"
 PRODUCTION_CIV_AND_MIL_FACTORIES:0 "民用与军用工厂: $KEY|H$"
 PRODUCTION_REQ_CONSUMER_GOODS_FACTORIES:0 "必要消费品工厂: $KEY|H$"
 PRODUCTION_MATERIAL_COST_DESC:0 "§T这条生产线使用$AMOUNT|0H$单位$MATERIAL|H$。§!"
 PRODUCTION_MATERIAL_COST_LACKING_DESC:2 "§T还需要$AMOUNT|0H$以充分发挥效率.§!\n生产将会以§R减速§!继续。"
 PRODUCTION_LINE_CANCEL:0 "§G单击§H撤销§!这条生产线。§!\n§Gshift+单击§H撤销§!所有生产线§!"
 PRODUCTION_CREATE_VARIANT:0 "§H建造衍生型§!"
 PRODUCTION_CANCEL_CONSTRUCTION:0 "§T取消此次建设。§!"
 PRODUCTION_VARIANT_OBSOLETE_YES:1 "复役"
 PRODUCTION_VARIANT_OBSOLETE_NO:1 "退役"
 PRODUCTION_VARIANT_OBSOLETE_YES_DESC:0 "§G单击§!让此衍生型再次投入使用，把它标记为最新型装备。"
 PRODUCTION_VARIANT_OBSOLETE_NO_DESC:0 "§G单击§!让此衍生型停止使用，把他标记为过时装备。"
 TRADE_FACTORIES_VALUE:0 "$VALUE$/$TOT$"
 CONFIRMCANCELPRODUCTIONLINE_TITLE:0 "撤销生产线"
 CONFIRMCANCELPRODUCTIONLINE_DESC:0 "你确定要§R撤销§!这条生产线吗？"
 CONFIRMCANCELALLPRODUCTIONLINE_TITLE:0 "撤销所有生产线"
 CONFIRMCANCELALLPRODUCTIONLINE_DESC:0 "你确定要§R撤销§!所有生产线吗?"
 CONFIRM_SWITCH_PRODUCTION_MODEL_TITLE:0 "切断设备"
 CONFIRM_SWITCH_PRODUCTION_MODEL_DESC:0 "你确定要§R切断§!设备吗？这将使你失去$DAYS|R$天的产量。"
 CONFIRMCANCELCONSTRUCTION_TITLE:0 "取消建设"
 CONFIRMCANCELCONSTRUCTION_DESC:0 "你确定要§R取消§!在$REGION|H$的$CONSTRUCTION|H$建设吗?"
 CONFIRMCANCELCONSTRUCTIONS_TITLE:0 "取消建设"
 CONFIRMCANCELCONSTRUCTIONS_DESC:0 "你确定要§R取消§!所有建设吗？"
 INFINITY:0 "£infinity_icon"
 PRODUCTION_EQUIPMENT_NEED:0 "需要: $AMOUNT|Y$"
 PRODUCTION_DEPLOY_TO_BASE:0 "部署港口: $BASE|H$"
 PRODUCTION_DEPLOY_TO_FLEET:0 "部署舰队: $FLEET|H$"
 PRODUCTION_NAVAL_DEPLOYMENT_FLEET_INVALID_BASE:0 "部署目标舰队$FLEET|H$无基地。"
 PRODUCTION_NAVAL_DEPLOYMENT_FLEET:0 "部署目标舰队$FLEET|H$到$STATE|H$的基地。"
 PRODUCTION_NAVAL_DEPLOYMENT_BASE:0 "在$STATE|H$部署目标基地。"
 PRODUCTION_NAVAL_DEPLOYMENT_INVALID_BASE:0 "无部署目标"
 PRODUCTION_NAVAL_DEPLOYMENT_NOT_DEPLOYABLE:0 "无法部署"
 PRODUCTION_NAVAL_DEPLOYMENT_AUTO_DEPLOYMENT:0 "自动"
 PRODUCTION_NAVAL_DEPLOYMENT_SCRAPPING:0 "废弃"
 PRODUCTION_NAVAL_DEPLOYMENT_SCRAPPING_DESC:0 "无有效基地可部署。单位在完成后将被废弃。"
 PRODUCTION_NAVAL_DEPLOYMENT_STOCKPILING:0 "储备"
 PRODUCTION_RIGHT_CLICK_TO_ZOOM:0 "§G右击转入省份§!"
 WEEKLY_PRODUCTION:0 "每周产量"
 PRODUCTION_WORKING_FACTORIES:0 "这是你当前一条生产线运作的工厂数量。"
 PRODICTION_MIC_TRANSFERED:0 "我们的$AMOUNT|Y$个工厂正在被$OVERLORD|Y$使用。"
 PRODICTION_MIC_RECEIVED_FROM_SUBJECT:0 "$AMOUNT|Y$个军用工厂来自于我们的附庸。"
 PRODICTION_MIC_SENT_TO_OVERLORD:0 "我们的$AMOUNT|R$个军用工厂供宗主国使用，我们只剩下了$LEFT|H$个。"
 PRODUCTION_CIVILIAN_FACTORIES_AVAILABLE:0 "可以用来建设: $VALUE|Y$"
 PRODUCTION_CIVILIAN_FACTORIES_CURRENTLY:0 "正在使用中: $VALUE|R$"
 PRODUCTION_MAX_EFFICIENCY_BASE:0 "基础上限: $VALUE|Y%$"
 PRODUCTION_MAX_EFFICIENCY_TOT:0 "£prod_eff_cap 生产效率上限: $VALUE|Y%$"
 PRODUCTION_MAX_EFFICIENCY_HINT:0 "£prod_eff_cap 生产效率上限你£prod_eff  生产效率的最大值，可通过£tech_mod 技术增加。"
 PRODUCTION_RESOURCES_PER_FACTORY:0 "§H每个工厂生产资源:§!"
 PRODUCTION_MATERIAL_NO_WASTE:0 "生产线没有浪费该资源。"
 PRODUCTION_MATERIAL_WASTE:0 "生产线正浪费$WASTE|R2$该资源。"
 PRODUCTION_SPEED:0 "生产速度: $SPEED|Y$"
 PRODUCTION_SPEED_MODIFIERS:0 "§Y产量修正:§!"
 INDUSTRIAL_CAPACITY_FACTOR:0 "工厂产量: $VALUE|Y$"
 INDUSTRIAL_CAPACITY_FACTOR_MODIFIERS:0 "工厂产量修正:"
 INDUSTRIAL_PROGRESS:0 "$BUILDING|H$$PROGRESS|0H$/$COST|0H$ ( $VALUE|0%H$ )完成。"
 INDUSTRIAL_PROGRESS_REPAIR:0 "$BUILDING|H$ 修复进度: $PROGRESS|%0H$"
 INDUSTRIAL_BASE_FACTORY_OUTPUT:0 "基础工厂产量: $VALUE|H$"
 INDUSTRIAL_BASE_SPEED:0 "$FACTORIES|0H$工厂产量: $VALUE|H$"
 PROD_COST_VALUE:0 "£production_cost  $VALUE$"
 NAVPROD_COST_VALUE:0 "£navprod_cost  $VALUE$"
 PRODUCTION_CIVILIAN_FACTORIES_OWNED:0 "拥有: $VAL|H$"
 PRODUCTION_CIVILIAN_FACTORIES_BORROWED:0 "源自出口: +$VAL|H$"
 PRODUCTION_CIVILIAN_FACTORIES_FROM_SUBJECTS:0 "源自附庸 +$VAL|H$"
 PRODUCTION_CIVILIAN_FACTORIES_SENT_TO_MASTER:0 "给宗主国: $VAL|R$"
 PRODUCTION_EQUIPMENT_TOTAL_NEED:0 "总需求: $VALUE|0Y$"
 PRODUCTION_EQUIPMENT_TOTAL_NEED_FILLED:0 "总需求: §G满足§!"
 PRODUCTION_EQUIPMENT_TOTAL_NEED_UPGRADE:0 "升级需求: $VALUE|0Y$"
 PRODUCTION_EQUIPMENT_DAILY_BALANCE:0 "每日结余: $VALUE|=2Y$"
 PRODUCTION_EQUIPMENT_FILL_ESTIMATION:0 "依照现在的每日余额，我们将在$VALUE|0Y$天内§Y满足§!需求。"
 PRODUCTION_EQUIPMENT_FILLED:0 "现在我们的需求已§G满足§!"
 PRODUCTION_EQUIPMENT_LOSSES:0 "我们昨天失去$VALUE|R$装备。"
 PROD_LINE_PLANE_DEST_RESERVES:0 "该生产线飞机现已移入后备队。"
 PROD_LINE_PLANE_DEST_UPGRADING:0 "该生产线飞机现已用来升级。"
 PROD_LINE_PLANE_DEST_REINFORCEMENT:0 "该生产线飞机现已用来增援"
 PROD_LINE_LAND_DEST_RESERVES:0 "该生产线设备现已储备"
 PROD_LINE_LAND_DEST_UPGRADING:0 "该生产线设备现已用来升级"
 PROD_LINE_LAND_DEST_REINFORCEMENT:0 "该生产线装备现已用来增援"
 CONFIRM_REMOVE_BUILDING_LEVEL_TITLE:0 "移除建筑"
 CONFIRM_REMOVE_BUILDING_LEVEL_DESC:0 "你确定要§R移除§!此建筑？"
 CONFIRM_REMOVE_CONSTRUCTION_LEVEL_TITLE:0 "取消建设"
 CONFIRM_REMOVE_CONSTRUCTION_LEVEL_DESC:0 "你确定要§R取消§!此项建设？"
 CONFIRM_REMOVE_CONVERSION_LEVEL_TITLE:0 "取消转换"
 CONFIRM_REMOVE_CONVERSION_LEVEL_DESC:0 "你确定要§R取消§!此次转换？"
 CONFIRM_ADD_CONVERSION_LEVEL_TITLE:0 "开始转换"
 CONFIRM_ADD_CONVERSION_LEVEL_DESC:0 "你确定要§R转换t§!该建筑？"
 PRODUCTION_EFFICIENCY_GAIN_BASE:0 "每日基础收入: $VAL|%Y$"
 PRODUCTION_RESOURCE_FACTOR:0 "缺少资源: $VAL|%+$"
 PRODUCTION_OUTPUT_EXPLAIN:0 "我们的$FACTORIES|Y$ £factory_item 军用工厂提供$OUTPUT|Y$ £production_cost 。\n$ITEM|Y$花费$ITEM_COST|2Y$£production_cost ，这表示我们的产量是$PERTIMEPERIOD$。\n"
 PRODUCTION_OUTPUT_EXPLAIN_NAVAL:0 "我们的$FACTORIES|Y$£naval_factory_icon 海军船坞提供$OUTPUT|Y$ £navprod_cost 。\n$ITEM|Y$花费$ITEM_COST|2Y$ £navprod_cost ，这表示我们的产量是$PERTIMEPERIOD$。\n"
 PRODUCTION_UNITS_PER_DAY:0 "$UNITS|Y$单位/日"
 PRODUCTION_UNITS_PER_WEEK:0 "$UNITS|Y$单位/周"
 PRODUCTION_UNITS_PER_MONTH:0 "$UNITS|Y$单位/月"
 PRODUCTION_UNITS_PER_YEAR:0 "$UNITS|Y$单位/年"
 PRODUCTION_FACTORY_ASSIGN_DESC:0 "单击分配£factory_item $FACTORIES|Y$军用工厂到该生产线。这将使总产量£production_cost 变为$OUTPUT|Y$/天。"
 PRODUCTION_DOCKYARD_ASSIGN_DESC:0 "单击分配£naval_factory_icon $FACTORIES|Y$海军船坞到该生产线。这将使总产量£navprod_cost 变为$OUTPUT|Y$/天。"
 PRODUCTION_BASE_OUTPUT:0 "基础产量: $VALUE|Y$ x$MUL$"
 PRODUCTION_EFF_GAIN_HINT:0 "§Y效率增长速度修正:§!"
 CARRIER_AIR_WING_COMPOSITION_TITLE:0 "设定该航母空军部队的默认编组"
 CARRIER_AIR_WING_LIMIT_UNDER:0 "$COUNT|Y$/$LIMIT$"
 CARRIER_AIR_WING_LIMIT_MATCH:0 "$COUNT|G$/$LIMIT$"
 CARRIER_AIR_WING_LIMIT_OVER:0 "$COUNT|R$/$LIMIT$"
 CARRIER_AIR_WING_LIMIT_DESC:0 "飞机/航母载机容量"
 CARRIER_AIR_WING_LIMIT_DESC_UNDER:0 "§Y该航母的载机容量没有完全利用§!"
 CARRIER_AIR_WING_LIMIT_DESC_OVER:0 "§R超过该航母载机容量。驻扎其中的空军部队将会遭受惩罚§!"
 CARRIER_AIR_WING_INCREASE:0 "增加空军部队数量\n§GCtrl+单击增加§! §H5§!\n§GShift+单击增加§! §H10§!"
 CARRIER_AIR_WING_DECREASE:0 "减少空军部队数量\n§GCtrl+单击减少§! §H5§!\n§GShift+单击减少§! §H10§!"
 PRODUCTION_ENTRY_NEW:0 "§G全新§!"
 PRODUCTION_ENTRY_OUTDATED:0 "§H过时§!"
 PRODUCTION_LINE_CHANGE:0 "§G单击§H改变§!生产的装备。\n如果你转而生产同一装备的新型号，将会保留一些生产效率。\n§!§R但你会失去该生产线当前的所有进度§!"
 PRODUCTION_EQUIPMENT_FILTER:0 "步兵和炮兵装备"
 PRODUCTION_ARMOR_FILTER:0 "装甲车辆"
 PRODUCTION_AIR_FILTER:0 "飞行器"
 PRODUCTION_CAPITAL_SHIPS_FILTER:0 "主力舰"
 PRODUCTION_SCREEN_SHIPS_FILTER:0 "屏卫舰"
 PRODUCTION_OTHER_SHIPS_FILTER:0 "其他舰种"
 PRODUCTION_FILTER_ARMS_FACTORIES:0 "军用工厂使用"
 PRODUCTION_FILTER_DOCKYARDS:0 "海军船坞使用"
 PRODUCTION_NAVAL_DEPLOYMENT_STATE_NAME:0 "$STATE$ ($LVL|Y$)"
